// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoErp.Data;

#nullable disable

namespace ProjetoErp.Migrations
{
    [DbContext(typeof(ProjetoDBContext))]
    [Migration("20230407212655_tabelaClientes")]
    partial class tabelaClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoErp.Models.ClienteModel", b =>
                {
                    b.Property<int>("id_CT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_CT"));

                    b.Property<string>("enderecoEmail_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enderecoLocal_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_CT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTelefone_CT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_CT");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProjetoErp.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("id_FN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_FN"));

                    b.Property<int?>("anoContratacao_FN")
                        .HasMaxLength(250)
                        .HasColumnType("int");

                    b.Property<string>("cargo_FN")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("documentoCpf_FN")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("enderecoEmail_FN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enderecoLocal_FN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_FN")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("numeroTelefone_FN")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("salario_FN")
                        .HasMaxLength(250)
                        .HasColumnType("float");

                    b.HasKey("id_FN");

                    b.ToTable("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
